POST http://localhost:3030/login
Content-Type: application/json

{
    "email": "b",
    "password": "b"
}

###
GET http://localhost:3030/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWUiOiJiIiwiZW1haWwiOiJiIiwiaWF0IjoxNjg1MDM2MTY1LCJleHAiOjE2ODUwMzYxODV9.4COi6YaY86j1trCmNeXIFwm6m2jB9WFC1ZdkJbkeY_Y


###
GET http://localhost:3030/token


###
DELETE http://localhost:3030/logout